### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [leolastikka/open_world#1]
Hello, I just wanted to confirm if this project is released under the ISC license ? I would like to study it to learn from it. It seems like a wonderful project and learning resource. Thank you.

**Comment by leolastikka** [comment]
Hello
Yes it is, I just created a licence file in the project root and updated readme (80d62d634b2f456d118bdf62c8c47c3d2542c81f). Haven't done this before because I wasn't expecting anyone to find it :smile: but feel free to study it.
